#!/bin/bash

# sends system files to their spots
# -r options grabs system files form their spots

usage() { echo "Usage: [-all] [-bash] [-display] [-terminal]" 1>&2; exit 1; }

function bash()
{
    echo "~/.bashrc"
    if [ -v reverse ]; then
        echo "cp ~/.bashrc ~/code/dotfiles/bash"
    else
        echo "cp ~/code/dotfiles/bash/.bashrc ~/"
    fi
    echo "~/.bash_profile"
    if [ -v reverse ]; then
        echo "cp ~/.bash_profile ~/code/dotfiles/bash"
    else
        echo "cp ~/code/dotfiles/bash/.bash_profile ~/"
    fi
}

function term()
{
    echo "alacritty"
    echo "~/.bashrc"
    echo "~/.bash_profile"
    echo "starship"
    echo "nvim"
    echo "moc"
    echo "neofetch"
    echo "vifm"
    echo "tmux"
}

function sys()
{
    echo "pacman.conf"
    echo "~/.xinitrc"
    echo "dwm"
    echo "dmenu"
    echo "/etc/fstab"
    echo "tubthumping"
}

function web()
{
    echo "httpd"
}

function other()
{
    echo "dolphin"
    echo "mpd"
    echo "ffmpeg"
}

function get_all()
{
    for func in $(grep "^function" $0)
    do
        if [ $func != "function" ] && [ $func != "get_all()" ]; then
            ${func::-2}
        fi
    done
}

while getopts ":aborstw" opt; do
    case $opt in
        r)
            reverse=1
            ;;
        a)
            get_all
            ;;
        b)
            bash
            ;;
        o)
            other
            ;;
        s)
            sys
            ;;
        t)
            term
            ;;
        w)
            web
            ;;
        *)
            usage
            ;;
    esac
done
# cp bash/bashrc ~/.bashrc
# cp alacritty/alacritty.yml ~/.config/alacritty
# cp neofetch/config.conf ~/.config/neofetch
# cp -r nvim ~/.config/nvim
# cp starship/starship.toml ~/.config
# cp -r vifm ~/.config
