#!/bin/bash
# start my favorite tmux sessions

mode=$1

function pychm() {
    echo "starting tmux chm python development"
    tmux new-session -d -s "pychm"
    tmux rename-window -t 0 "git"
    tmux send-keys -t "git" "cd ~/code/collections/automations" C-m
    tmux new-window -t "pychm":1 -n "python"
    tmux send-keys -t "python" "cd ~/code/collections/automations" C-m
    tmux attach-session -t "pychm"
}

function pythm() {
    echo "starting tmux for thm python development"
    tmux new-session -d -s "pythm"
    tmux rename-window -t 0 "git"
    tmux send-keys -t "git" "cd ~/code/thm"
    tmux new-window -t "pythm":1 -n "makevideos"
    tmux send-keys -t "makevideos" "cd ~/code/thm" C-m "nvim makevideos.py" C-m
    tmux new-window -t "pythm":2 -n "sample-files"
    tmux send-keys -t "sample-files" "cd /tub/brendan-project-archive/TheHistoryMakers/samples" C-m
    tmux attach-session -t "pythm"
}

function pygen() {
    echo "starting tmux with default python config"
    tmux new-session -d -s "pygen"
    tmux rename-window -t 0 "git"
    tmux send-keys -t "git" "cd ~/code"
    tmux new-window -t "pygen":1 -n "python"
    tmux send-keys -t "python" "cd ~/code" C-m "python" C-m
    tmux new-window -t "pygen":2 -n "nvim"
    tmux send-keys -t "nvim" "cd ~/code" C-m "nvim" C-m
    tmux attach-session -t "pygen"
}
if [ $mode == "pychm" ]
then
    pychm
elif [ $mode == "pythm" ]
then
    pythm
elif [ $mode == "pygen" ]
then
    pygen
fi

